name: Build OpenWrt Firmware

permissions:
  contents: write

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3

      - name: Download OpenWrt source code
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout $(git tag | grep -E '^v[0-9]+\.[0-9]+$' | sort -V | tail -n 1) # Checkout the latest stable version

      - name: Update and install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          cp openwrt/.config .config
          make defconfig

      - name: Build firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-firmware
          path: openwrt/bin/targets
